{% set name = "ocap" %}
{% set version = "0.3.9.post1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ocap-{{ version }}.tar.gz
  sha256: 24a88dc6e8a7e2a8a502d5d853a948de7345c3a63b571080f2c99eab33f500ba

build:
  entry_points:
    - ocap = owa.ocap.record:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - owa-cli
    - owa-env-desktop
    - owa-env-gst

test:
  imports:
    - owa.ocap
  commands:
    - pip check
    - ocap --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-world-agents/open-world-agents
  summary: High-performance, omnimodal desktop recorder for Windows
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
