{% set name = "ocap" %}
{% set version = "0.3.9" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ocap-{{ version }}.tar.gz
  sha256: 8085c55999ba21cf7415c07cf097a56abce6240034f0789f567346af0824918b

build:
  entry_points:
    - ocap = owa.ocap.record:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - owa-cli
    - owa-env-desktop
    - owa-env-gst

test:
  imports:
    - owa.ocap
  commands:
    - pip check
    - ocap --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-world-agents/open-world-agents
  summary: High-performance, omnimodal desktop recorder for Windows
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
